### ISSUE TITLE
Improve Attestation Demo Functionality

### ISSUE THREAD

**Issue by arp102** [NationalSecurityAgency/pelz#124]
- [x] Have the worker do something with the decrypted data (see #78).
- [x] Change the encryption format to bundle the DEK, TAG, and IV (and possibly the KEK id) with the encrypted data.
- [x] Move all of the new file encryption/decryption code from `pelz` (file_seal_encrypt_decrypt.c) to `appinitiator`.
- [x] Convert `README.txt` to Markdown format for consistency.
- [ ] ~~Possibly have the demo application encrypt the search result output using the public key of the "customer" who requested the search.~~
- [x] Use signed pelz requests for the attestation demo. (#127)
- [x] Use the peer enclave's `MRSIGNER` value for authentication on the attestation interface.
    - Quick version: check that both enclaves were signed with the same key
    - Longer version: compare the peer's MRSIGNER value to a known trusted cert file
        - Need to update the CLI to specify the cert file, figure out how to convert it to an MRSIGNER value, and get it into the enclave to do the comparison
- [x] Encrypt sensitive fields of pelz json messages on the attestation interface.

**Comment by bit-bender** [comment]
All of the improvements listed in this issue have been addressed (or removed), at least to the state that we can consider this issue closed.

Issue #132 was created to independently track potential future enhancements to how the MRSIGNER-based authentication is implemented.
