### ISSUE TITLE
Suggest documentation improvements

### ISSUE THREAD

**Issue by asd44622** [NationalSecurityAgency/pelz#128]
Hello,

In this issue, I have identified one minor typo that needs correction.

`executible` -> `executible` [INSTALL.md L83](https://github.com/NationalSecurityAgency/pelz/blob/8075f91e68f622a42055ad17bdf91056096cf335/INSTALL.md?plain=1#L83)

Thank you for your time and consideration in addressing these errors.
Best regards,
Melody

**Comment by b-carr** [comment]
Closed with GH-130.
