### ISSUE TITLE
Enclave to Enclave Attestation Demo

### ISSUE THREAD

**Issue by JWZeta** [NationalSecurityAgency/pelz#78]
Create a "worker enclave" for searching an encrypted object (start with a list of hashed words in a Linux file) for a keyword. We assume we're always searching structured data, so the list is formatted. The worker enclave would ask pelz to unwrap an FEK and send it back through a secure channel. Then the enclave would decrypt the file, search for an exact match of a hash of the keyword and return the count of the number of times the keyword appeared in the list. The FEK would be protected throughout. The enclave would not modify or save the list.

**Comment by bit-bender** [comment]
We now have a functional enclave to enclave attestation demo. Issue #124 addresses some key aspects re: the evolution of this demo.
